"""Add new fields to Campaign model

Revision ID: e849bd4a5f08
Revises: 
Create Date: 2024-10-16 04:03:17.730390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e849bd4a5f08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_docs', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('campaign_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('TnC', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('division', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nature', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adobe_camp_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('crm_camp_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('crm_camp_id')
        batch_op.drop_column('adobe_camp_id')
        batch_op.drop_column('nature')
        batch_op.drop_column('division')
        batch_op.drop_column('content')
        batch_op.drop_column('TnC')
        batch_op.drop_column('campaign_description')
        batch_op.drop_column('campaign_docs')

    # ### end Alembic commands ###
